[build]
  # Build directory - where the React app is located
  base = "afro-eats"
  
  # Build command to run
  command = "npm run build"
  
  # Directory where build artifacts are output
  publish = "build"

# Redirect all routes to index.html for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables for production
[build.environment]
  # React production build
  NODE_ENV = "production"
  
  # API Configuration
  REACT_APP_API_BASE_URL = "https://api.orderdabaly.com"
  # REACT_APP_STRIPE_PUBLISHABLE_KEY is set in Netlify dashboard environment variables for security
  
  # Build optimizations
  GENERATE_SOURCEMAP = "false"
  CI = "true"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache static assets
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    # Don't cache HTML files
    Cache-Control = "no-cache"

[[headers]]
  for = "/static/js/*"
  [headers.values]
    # Cache JavaScript files for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/css/*"
  [headers.values]
    # Cache CSS files for 1 year  
    Cache-Control = "public, max-age=31536000, immutable"